### ISSUE TITLE
Modify Deflate to use BinaryStdIn & BinaryStdOut

### ISSUE THREAD

**Issue by msbense** [msbense/DCP#1]
BinaryStdIn & BinaryStdOut contain methods for writing integers;
The I/O is already set for these classes by the time Deflate.compress()/expand() is run;
Huffman and LZW use those methods when they attach a header to the compressed data containing the
    length of the original message;
We should modify Deflate to use BinaryStdIn & BinaryStdOut to both add the integer headers,
    And send the data itself

**Comment by Connor-Devitt** [comment]
Fixed
