### ISSUE TITLE
Deflate creates an unknown compression method exception. Once fixed, deflate should work

### ISSUE THREAD

**Issue by Connor-Devitt** [msbense/DCP#2]
java.util.zip.DataFormatException: unknown compression method
    at java.util.zip.Inflater.inflateBytes(Native Method)
    at java.util.zip.Inflater.inflate(Inflater.java:238)
    at java.util.zip.Inflater.inflate(Inflater.java:256)
    at Runnables.Deflate.expand(Deflate.java:68)
    at DCPWrapper.DCPWrapper.DeflateDecompress(DCPWrapper.java:225)
    at DCPWrapper.DCPWrapper.client(DCPWrapper.java:158)
    at DCPWrapper.DCPWrapper.main(DCPWrapper.java:48)

**Comment by Connor-Devitt** [comment]
Problems exists only for the decompression

**Comment by msbense** [comment]
I added a library that helps us with IO, and implemented it in Deflate.java. So we know that the compressed data itself is being written correctly.
    When I made this change, java threw a "incorrect header check" exception so it sounds like we wrote the lengths wrong. 
    I'll see if replacing the BinaryStd readInt() methods with java standard library methods will do anything

**Comment by msbense** [comment]
BTW the Incorrect Header Check happened in the same place that "unknown compression method" happened.

**Comment by msbense** [comment]
and I just realized there's no need at all to write "headers" to the compressionOutputStream. In the else if clause for Deflate, we can just read two ints the same way we read the filename and algorithm name

**Comment by msbense** [comment]
Fixed it, deflate works now. Will merge my branch into master
